# part 5

# psi is the quantity we want to make inference about and is defined as a function of mu, Sigma and xi
psifn = function(muval, xival, Sigmaval){
  # muval is a vector of means
  # xival is a precision matrix associated with variance matrix Sigmaval
  # the code here depends on the psi function we wish to make inference about
  psi=muval[1]
  return(psi)
}

prior_psi = function(Nprior, mu_prior, Sigma_prior, xi_prior){
  # obtaining the prior density of psi.
  # (ideally use the data generated from the sample)
  
  # compute prior sample of psi values 
  prior_psi_vals = numeric(Nprior)
  for (i in 1:Nprior){
    prior_psi_vals[i] = psifn(mu_prior[i], xi_prior[[i]], Sigma[[i]])
  }
  
  newlist = list("prior_psi_vals" = prior_psi_vals,
                 "prior_psi_lower_bd" = min(prior_psi_vals),
                 "prior_psi_upper_bd" = max(prior_psi_vals))
}

prior_psi_plot_vals = function(numcells = 100, Nprior, mprior = 7, 
                               mu_prior, Sigma_prior, xi_prior){
  # getting values from the plot
  prior_vals = prior_psi(Nprior, mu_prior, Sigma_prior, xi_prior)
  prior_psi_vals = prior_vals$prior_psi_vals
  prior_psi_upper_bd = prior_vals$prior_psi_upper_bd
  prior_psi_lower_bd = prior_vals$prior_psi_lower_bd
  
  delta_psi = (prior_psi_upper_bd - prior_psi_lower_bd) /numcells 
  breaks = seq(prior_psi_lower_bd, prior_psi_upper_bd, by = delta_psi)

  prior_psi_hist = hist(prior_psi_vals, breaks, freq = F)
  prior_psi_mids = prior_psi_hist$mids
  prior_psi_density = prior_psi_hist$density 
  
  # smoothed plot of the prior density of psi
  # if a plot is too rough smooth by averaging
  # mprior = an odd number of points to average prior density values, (mprior=1,3,5,...) by averaging
  # the density value, (mprior-1)/2 values to the left and (mprior-1)/2 values to the right
  prior_psi_dens_smoothed = prior_psi_density
  halfm = (mprior-1)/2
  for(i in (1+halfm):(numcells-halfm)){
    sum = 0
    for (j in (-halfm):halfm){
      sum = sum + prior_psi_density[i+j]
    }
    prior_psi_dens_smoothed[i]=sum/mprior  
  }
  newlist = list("prior_psi_mids" = prior_psi_mids, 
                 "prior_psi_dens_smoothed" = prior_psi_dens_smoothed,
                 "psi_breaks" = breaks,
                 "delta_psi" = delta_psi)
}

post_psi = function(Npostimp, numcells = 100, imp_mu, imp_Sigma, imp_xi, imp_weights,
                    breaks){
  
  # compute sample of psi values generated by the importance sampler 
  imp_psi_vals = numeric(Npostimp)
  for (i in 1:Npostimp){
    imp_psi_vals[i] = psifn(imp_mu[i],imp_xi[[i]],imp_Sigma[[i]])
  }
  
  # compute the estimate of the posterior cdf of psi
  nbreaks = numcells+1
  post_psi_cdf = rep(0, nbreaks)
  for(i in 2:nbreaks){
    for(j in 1:Npostimp){
      if(imp_psi_vals[j] <= breaks[i]){
        post_psi_cdf[i] = post_psi_cdf[i] + imp_weights[j]
      }
    }
  }
  
  # check interval (prior_psi_lower_bd, prior_psi_upper_bd) covers importance sampling values of psi.
  post_psi_upper_bd = min(imp_psi_vals) - breaks[1] # should be positive
  post_psi_lower_bd = max(imp_psi_vals) - breaks[nbreaks] # should be negative
  
  newlist = list("post_psi_upper_bd" = post_psi_upper_bd, "post_psi_lower_bd" = post_psi_lower_bd,
                 "post_psi_cdf" = post_psi_cdf)
  
  return(newlist)
}

post_psi_plot_vals = function(Npostimp, numcells = 100, mpost = 5,
                              imp_mu, imp_Sigma, imp_xi, imp_weights, breaks,
                              delta_psi){
  
  post_psi_vals = post_psi(Npostimp, numcells, imp_mu, imp_Sigma, imp_xi, imp_weights, breaks)
  post_psi_cdf = post_psi_vals$post_psi_cdf
  
  # compute posterior density of psi
  post_psi_density = diff(post_psi_cdf)/delta_psi
  
  # smoothed plot of the posterior density of psi
  # if a plot is too rough smooth by averaging
  # mprior = an odd number of points to average prior density values, (mprior=1,3,5,...) by averaging
  # the density value, (mpost-1)/2 values to the left and (mpost-1)/2 values to the right
  post_psi_dens_smoothed = post_psi_density
  halfm = (mpost-1)/2
  for (i in (1+halfm):(numcells-halfm)){
    sum = 0
    for (j in (-halfm):halfm){
      sum = sum + post_psi_density[i+j]
    }
    post_psi_dens_smoothed[i] = sum/mpost  
  }
  
  return("post_psi_dens_smoothed" = post_psi_dens_smoothed)
}

rbr_psi = function(numcells = 100, prior_psi_dens_smoothed, post_psi_dens_smoothed){
  # obtain the relative belief ratio of psi
  RB_psi = rep(0, numcells)
  for (i in 1:numcells){
    if (prior_psi_dens_smoothed[i] != 0){
      RB_psi[i] = post_psi_dens_smoothed[i]/prior_psi_dens_smoothed[i]}
  }
  return(RB_psi)
}

############################

# part 6

# estimate of true value of psi from the relative belief ratio
# may not turn this into a function bc of how simple it is.
#RBest = prior_psi_mids[which.max(RB_psi)]

################################################################
# estimating plausible region.the values of psi where the RB > 1
# note that this may not be an interval if RB is multimodal

plausible_region_est = function(prior_psi_mids, RB_psi, post_psi_dens_smoothed,
                                delta_psi){
  # estimating plausible region
  plaus_region = ifelse(RB_psi > 1, prior_psi_mids, 0)
  
  # getting the interval instead
  nonzero_values = plaus_region[plaus_region != 0]
  plaus_interval = c(nonzero_values[1], nonzero_values[length(nonzero_values)])
  
  # getting the posterior content of the plausible region
  plaus_content = 0
  for(i in 1:length(prior_psi_mids)){
    if(RB_psi[i] > 1){
      plaus_content = plaus_content + post_psi_dens_smoothed[i]
    }
  }
  plaus_content = plaus_content * delta_psi
  
  newlist = list("plaus_region" = plaus_region,
                 "plaus_interval" = plaus_interval,
                 "plaus_content" = plaus_content)
  return(newlist)
}

psi_hypothesis_test = function(psi_0 = -2, prior_psi_mids, RB_psi, post_psi_dens_smoothed){
  
  psi_0_index = which.min(abs(prior_psi_mids - psi_0))
  
  # evidence for or against psi0
  if(RB_psi[psi_0_index] > 1){
    psi_message = paste("RB of psi_0 = ",RB_psi[psi_0_index]," so there is evidence in favor of H_0 : psi = ",
                  psi_0, sep ="")
  }
  else if(RB_psi[psi_0_index] < 1){
    psi_message = paste("RB of psi_0 = ", RB_psi[psi_0_index]," so there is evidence against H_0 : psi = ",
                  psi_0, sep = "")
  }
  else if(RB_psi[psi_0_index] == 1){
    psi_message = paste("RB of psi_0 = ", RB_psi[psi_0_index],
          " so there is no evidence either in favor of or against H_0 : psi = ",
          psi_0, sep = "")
  }
  
  # compute the evidence concerning strength H_0 : psi = psi_0
  indices = which(RB_psi <= RB_psi[psi_0_index])
  # Compute the strength
  strength_psi_0 = sum(post_psi_dens_smoothed[indices]) * delta_psi
  strength_msg = paste("Strength of the evidence concerning H_0 : psi= psi_0 = ", strength_psi_0, sep = "")

  newlist = list("psi_message" = psi_message, "indices" = indices, "strength_message" = strength_msg)
  
  return(newlist)
}


##################################################
# testing functions

mu_prior = sample_prior_vals$mu_matrix
Sigma_prior =  sample_prior_vals$Sigma_mat[]
xi_prior = sample_prior_vals$xi_mat

prior_psi_vals = prior_psi_plot_vals(numcells = 100, Nprior = Nprior, mprior = 7, 
                                     mu_prior = mu_prior, 
                                     Sigma_prior = Sigma_prior, xi_prior = xi_prior)

# obtain importance sample generated in Part 3
imp_mu = imp_vals$mu_xi
imp_Sigma=imp_vals$Sigma
imp_xi = imp_vals$xi
imp_weights = imp_vals$weights_vector

post_psi_vals = post_psi_plot_vals(Npostimp = Npostimp, numcells = 100, mpost = 5,
                                   imp_mu , imp_Sigma, imp_xi, imp_weights,
                                   breaks = prior_psi_vals$psi_breaks,
                                   delta_psi = prior_psi_vals$delta_psi)

rbr_psi_vals = rbr_psi(numcells = 100, 
                       prior_psi_dens_smoothed = prior_psi_vals$prior_psi_dens_smoothed, 
                       post_psi_dens_smoothed = post_psi_vals)

#############################################################################################################
# The plots side-by-side
par(mfrow = (c(1, 3)))
plot(prior_psi_vals$prior_psi_mids, prior_psi_vals$prior_psi_dens_smoothed, type = "l", 
     xlab = "psi", ylab = "density", col = "red", main="The prior density of psi")
plot(prior_psi_vals$prior_psi_mids, post_psi_vals, type = "l", 
     xlab = "psi", ylab = "density", col = "blue", main="The posterior density of psi" )
plot(prior_psi_vals$prior_psi_mids, rbr_psi_vals, type = "l", xlab = "psi", 
     ylab = "RBR", col = "green", main="The relative belief ratio of psi")

# alternative plots
par(mfrow=(c(1, 2)))
max_val = plyr::round_any(max(c(prior_psi_vals$prior_psi_dens_smoothed, post_psi_vals)), 
                          accuracy = 0.1, f = ceiling)
ylim_vals = c(0, max_val)

plot(prior_psi_vals$prior_psi_mids, prior_psi_vals$prior_psi_dens_smoothed, type = "l", 
     xlab = "psi", ylab = "density", col = "red", main="The prior density of psi",
     ylim = ylim_vals)
lines(prior_psi_vals$prior_psi_mids, post_psi_vals, type = "l", 
     xlab = "psi", ylab = "density", col = "blue", main="The posterior density of psi")
plot(prior_psi_vals$prior_psi_mids, rbr_psi_vals, type = "l", xlab = "psi", 
     ylab = "RBR", col = "green", main="The relative belief ratio of psi")



########################################

prior_psi_mids = prior_psi_vals$prior_psi_mids
RB_psi = rbr_psi_vals
post_psi_dens_smoothed = post_psi_vals
delta_psi = prior_psi_vals$delta_psi

RBest = prior_psi_mids[which.max(RB_psi)]

plausible_region_est(prior_psi_mids, RB_psi, post_psi_dens_smoothed,
                     delta_psi)

hypo_test = psi_hypothesis_test(psi_0 = -2, prior_psi_mids, RB_psi, post_psi_dens_smoothed)
hypo_test
  